sudo: required
services:
  - docker

language: generic

script:
  - docker build . -t fooofei/netshoot-x86_64:latest
after_script:
  - docker images

deploy:
  - provider: script
    script: bash ./scripts/docker_push.sh
    on:
      branch: x86_64
arch:
  - amd64
os: linux 
