name: buildx

# 容器里嵌套容器就不是 aarch64 了，不再构建 aarch64
on:
  pull_request:
    branches: []
  push:
    branches: []
    tags:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        id: runcmd
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: aarch64
          distro: ubuntu20.04
          # setup docker env from https://github.com/uraimo/run-on-arch-action/issues/33
          # https://github.com/Rothamsted/knetminer/blob/master/.github/workflows/docker-test.yml
          run: |
            apt-get -yq update
            apt-get -yq upgrade
            apt-get -yq install docker.io
            bash ./scripts/build.sh


            
